---
title: "Tree-based Classifiers"
output: html_notebook
---


## Overview

As the capstone for our discussion of classification you will compare how well different classifiers can predict whether someone has a salary above $50,000. The data can be found in the [adults.csv]() file on the course webpage, and were extracted from Census Bureau records. The data set contains the following variables:

Variable | Description
-----|---------------------------------------------------------
`age`     | Age of the individual (years)
`workclass` | Type of employer (Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, or Never-worked)
`education`| The highest level of education achieved for that individual
`marital.status` | Marital status of the individual
`occupation` | Occupation of the individual
`relationship` | Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried
`race` | White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black
`sex`     | Biological sex: Female or Male
`capital.gain` | Capital gains recorded
`capital.loss` | Capital Losses recorded
`hours.per.week` | Hours worked per week
`native.country` | Country of origin
`income` | `<=50K` or `>50K`


Note that many of the variables are categorical.

## Tasks

### 1

Create a training set consisting of 21,000 observations, and a test set consisting of the remaining observations. Name these data sets `train` and `test`, respectively.

### 2

Fit a classfication tree to the training data to predict XXX. What is the training error rate? How many terminal nodes does the tree have?

### 3

Create a plot of the tree.

### 4

Predict the response on the test data and produce a confusion matrix comparing the test labels (classes) to the predicted test labels. What is the test error rate?

### 5

Use the 10-fold cross-validation results to prune the tree. Obtain the training and test error rates for the pruned tree. How do these compare to the unpruned tree?

### 6

Apply bagging to this problem using the `randomForest` function in the `randomForest` R package. Note that you should set `mtry` equal to the number of attributes you are considering. What is the OOB error rate? 

### 7

Grow a random forest for this problem, setting `mtry` equal to the square root of the number of attributes that you're considering (you should round this to an integer). What is the OOB error rate?

### 8

Obtain the test error rates for your bagged tree and your random forest. How do they compare to the test error rates for pruned and unpruned trees?

### 9

A benchmark for any classifier is the error rate achieved by classifying all observations into the largest class using the entire data set. What is the benchmark error rate here? Are the above classifiers an improvement over this naive method?


