---
title: "Creating High Quality Graphics"
author: "CMSC 205, Winter 2017"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---
class: center, middle
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# What makes a good visualization?

---

# Tufte's graphical excellence...

- ...is the well designed presentation of interesting data - a matter of substance,
of statistics and of design.

- ...consists of complex data communicated with clarity, precision and efficiency.

- ...is that which gives to the viewer the greatest number of ideas in the shortest
time with the least ink in the smallest space.

- ...is nearly always multivariate.

- ...requires telling the truth about the data.

---

# Ross Ihaka's three principles

- If the "story" is simple, keep it simple.

- If the "story" is complex, make it look simple.

- Tell the truth.

---

# What makes a bad visualization?

---

# Howard Wainer's rules

When shoing data...

- Show as few data as possible

- Hide what data you do show (minimize the data-ink ratio)

In order to show data accurately...

- Ignore order and magnitude

---
class: center, middle

# Customizing graphics

---

# Tools for customization

- Titles

- Axis labels

- Color palettes

- Themes

---

# Titles

---

# Axis labels

---



